### ISSUE TITLE
don’t work on iPad

### ISSUE THREAD

**Issue by yanis791** [nuthrash/obsidian-html-plugin#10]
the obsidian shows "failed to load plugin obsidian-html-plugin" when click the enable bottom

**Comment by yanis791** [comment]
the obsidian shows "failed to load plugin obsidian-html-plugin" when click the enable bottom

**Comment by nuthrash** [comment]
Sorry, I do not have any workable iPad/iPhone/MAC device or simulator, therefore I never testing this plugin on these platforms.
In one of closed issue of this plugin, this kind of problem is caused by using some functions or libraries only available on desktop version. Did you ever enable this plugin on any other iPad/iPhone device? (In my Android devices, this plugin can be enabled without error)

I searched the Obsidian forum, it seems that there is no usable debugging console on these platforms.
- [Access the Obsidian console on iOS app](https://forum.obsidian.md/t/access-the-obsidian-console-on-ios-app/23476)

If someone is interesting in contributing and testing with their iPad devices, I’d be glad to accept contributions.

**Comment by yanis791** [comment]
Thank you for your reply. It's strange that when this plugin is enabled on the repository of the Mac that is synced to the cloud, the repository on the iPad can also work properly. Although I'm not sure why, the plugin can be used now anyway. Thank you for developing this plugin.

**Comment by FelipeRearden** [comment]
Trying to help you guys 😀 


@nuthrash  you can emulate Obsidian Mobile on desktop by executing this command on Console 

![image](https://user-images.githubusercontent.com/85180696/228306489-abff407f-553b-4deb-9921-5dd6a3513701.jpeg)

@nuthrash there is a plugin called [Obsidian Mobile Logging](https://github.com/shabegom/obsidian-mobile-logging) that copy the console log to a note. 

→  This way you can identify what is the error that the plugin is getting on Mobile and send to the developer 

--- 

I hope it helps 🙏
