### ISSUE TITLE
[BUG]: Error with left/right arrow keys when File Explorer is active

### ISSUE THREAD

**Issue by gasparschott** [nuthrash/obsidian-html-plugin#24]
I can navigate up and down the File Explorer, but if I use the left or right arrow keys the console (sometimes, but not always) records the following:

``` Uncaught TypeError: Cannot read properties of undefined (reading 'nodeName')
    at vw (app.js:1:750673)
    at e.onKeyArrowLeft (app.js:1:1673047)
    at e.handleKey (app.js:1:754582)
    at t.handleKey (app.js:1:754867)
    at e.onKeyEvent (app.js:1:755838)
    at eval (plugin:obsidian-html-plugin:11757:18)
```
and normal left/right arrow functionality (i.e., opening or closing folders) doesn't work.

Also, FWIW, Obsidian shows an error notification when the HTML Reader plugin is loaded:
```
"HTML Reader error: undefined"
```
with nothing recorded in the console, except sometimes this:

```
app.js:1 Uncaught TypeError: n.instanceOf is not a function
    at app.js:1:1476858
    at e.close (app.js:1:147712
```
which may or may not be related.

Using latest Obsidian on latest MacOS. Let me know what other information you may need.

**Comment by nuthrash** [comment]
Sorry, I have no MacOS machine, so I cannot reproduce your problem.
I test this plugin on my Windows machine, and still cannot reproduce your problem.

I guess this bug might be occurred by other plugin(s), because the HTML Reader plugin does not capture or handle any left/right arrow key.
Maybe you can disable some other plugin(s) to see if this problem still occur.

**Comment by gasparschott** [comment]
Thanks, I think the problem may well be with a plugin I’m testing. I can’t always reproduce the error either. You can close this issue.
