### ISSUE TITLE
Mathjax

### ISSUE THREAD

**Issue by pandichef** [nuthrash/obsidian-html-plugin#7]
I exported a Jupyter notebook from  VSCode with a LaTeX formula and it doesn't render correctly in Obsidian.
[Example File](https://deleteme-z4xq4hvfe.s3.amazonaws.com/main2.html)
The formula renders in Chrome, but not in Obsidian.

**Comment by nuthrash** [comment]
> The formula renders in Chrome, but not in Obsidian.

Do you mean this?
```markdown
$$y=x^2$$
```
Maybe you expect the formula is "y=x<sup>2</sup>"?

If Yes, that is because the Operating Mode of this plugin is switched to one of less unrestricted modes, that means the scripting used by Mathjax would be worked properly.

When I switch the [Operating Mode](https://github.com/nuthrash/obsidian-html-plugin#operating-mode) to "Unrestricted Mode", the formula seems correct

![Mathjax formula at Unrestricted Mode](https://user-images.githubusercontent.com/43021861/208223695-04bfea1c-f7a5-4bf2-a4b3-a499a06218b9.jpg)

The "Unrestricted Mode" is unrestricted for all bad guys and good guys, so be careful switching to this mode!

**Comment by pandichef** [comment]
The rendering works with "unrestricted mode", but then the note isn't copy-able.

**Comment by nuthrash** [comment]
> The rendering works with "unrestricted mode", but then the note isn't copy-able. It also mucks up theme coloring _throughout_ the front end Obsidian application.

The "unrestricted mode" imply this plugin would not change anything of the HTML files, and not isolate anything against other parts of Obsidian. So the HTML content are all rendered by Obsidian itself, and that would caused the results what you mentioned.
The scripting and isolation are mutually exclusive, so if you switch to less restricted modes, the formula would not rendered correctly.

**Comment by pandichef** [comment]
Ok.  It's too bad, but I get it.

**Comment by nuthrash** [comment]
> Ok. It's too bad, but I get it.

Hello, I found the solution to let scripting and isolation coexist, and next version 1.0.7 will apply this workaround.
